### ISSUE TITLE
File not found for module `version`, and couldn't read `hal_bindings.rs` (os error 2)

### ISSUE THREAD

**Issue by bobbbay** [first-rust-competition/first-rust-competition#101]
These past few days, I have been fiddling around with pulling in this project, to no success. I added `wpilib` as a dependency like so:

```toml
wpilib = { git = "https://github.com/first-rust-competition/first-rust-competition", package = "wpilib" }
```

But, on compilation, I get the following error(s):

```
❯ cargo r
   Compiling wpilib-sys v0.4.0 (https://github.com/first-rust-competition/first-rust-competition#3fb3d672)
error[E0583]: file not found for module `version`
  --> /home/bob/.cargo/git/checkouts/first-rust-competition-8a2dacc6f3073934/3fb3d67/wpilib-sys/src/lib.rs:16:1
   |
16 | mod version;
   | ^^^^^^^^^^^^
   |
   = help: to create the module `version`, create file "/home/bob/.cargo/git/checkouts/first-rust-competition-8a2dacc6f3073934/3fb3d67/wpilib-sys/src/version.rs" or "/home/bob/.cargo/git/checkouts/first-rust-competition-8a2dacc6f3073934/3fb3d67/wpilib-sys/src/version/mod.rs"

error: couldn't read /home/bob/.cargo/git/checkouts/first-rust-competition-8a2dacc6f3073934/3fb3d67/wpilib-sys/src/./hal_bindings.rs: No such file or directory (os error 2)
  --> /home/bob/.cargo/git/checkouts/first-rust-competition-8a2dacc6f3073934/3fb3d67/wpilib-sys/src/bindings.rs:21:1
   |
21 | include!("./hal_bindings.rs");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0583`.
error: could not compile `wpilib-sys` due to 2 previous errors
```

I am building on WSL, so it's possible that this is related to #85, but after reading the changes made, I doubt it. I'm curious if anyone else can compile the crate, considering that it's an internal error.

Here is the directory in question:

```
   inode Permissions Links Size Blocks User Date Modified Git Name                inode Permissions Links Size Blocks User Date Modified Git Name          inode Permissions Links Size Blocks User Date Modified Git Name
33913641 .rw-r--r--      1 1.3k      8 bob   6 May 14:31   --  bindings.rs    33913643 .rw-r--r--      1  535      8 bob   6 May 14:31   --  lib.rs
33913642 .rw-r--r--      1 5.6k     16 bob   6 May 14:31   --  hal_call.rs    33913644 .rw-r--r--      1 2.8k      8 bob   6 May 14:31   --  usage.rs
```

Thanks in advance.

**Comment by auscompgeek** [comment]
This project is not designed to be pulled in as a git dependency. You need a local checkout of the repo and then generate the `hal_bindings.rs` by running hal-gen.

**Comment by auscompgeek** [comment]
The bindings are included in the published crate, just not in the git repo.

Having a prepublish script seems like the way to go. We definitely don't want the binaries in the git repo, so need a prepublish step either way. The WPILib HAL headers are luckily written nicely enough that we haven't found the need to hand-roll the bindings.

**Comment by bobbbay** [comment]
Is it possibly preferable to build the bindings in a `build.rs`? I just want to depend on the newest features (e.g. `IterativeRobot`) without much hassle.

**Comment by auscompgeek** [comment]
We tried that, and realised that requiring teams have clang installed to build would be annoying, when they would otherwise just require a Rust toolchain and the roboRIO toolchain for the linker.
